/**
 * Cement comparison data — for programmatic SEO comparison pages.
 * Generates comparison pages × 2 locales.
 */

export interface CementComparison {
  slug: string;
  titleFr: string;
  titleEn: string;
  descFr: string;
  descEn: string;
  leftLabel: string;
  rightLabel: string;
  rows: { feature: string; leftVal: string; rightVal: string; }[];
  winnerFr: string;
  winnerEn: string;
}

export const COMPARISONS: CementComparison[] = [
  {
    slug: 'cpj45-vs-cpj55',
    titleFr: 'CPJ 45 vs CPJ 55 : Comparatif Complet',
    titleEn: 'CPJ 45 vs CPJ 55: Complete Comparison',
    descFr: 'Comparatif détaillé entre le ciment CPJ 45 et CPJ 55. Résistance, prix, usages, conditionnements.',
    descEn: 'Detailed comparison between CPJ 45 and CPJ 55 cement. Strength, price, uses, packaging.',
    leftLabel: 'CPJ 45',
    rightLabel: 'CPJ 55',
    rows: [
      { feature: 'Résistance (28j)', leftVal: '45 MPa', rightVal: '55 MPa' },
      { feature: 'Prix', leftVal: '1 500 DH/T', rightVal: '1 600 DH/T' },
      { feature: 'Finesse Blaine', leftVal: '≥ 350 m²/kg', rightVal: '≥ 380 m²/kg' },
      { feature: 'Début de prise', leftVal: '≥ 45 min', rightVal: '≥ 60 min' },
      { feature: 'Usage béton armé', leftVal: '✓ Optimal', rightVal: '✓ Excellent' },
      { feature: 'Usage génie civil', leftVal: 'Correct', rightVal: '✓ Recommandé' },
      { feature: 'Zone côtière', leftVal: 'Correct', rightVal: '✓ Recommandé' },
      { feature: 'Conditionnements', leftVal: 'Vrac, sacs, big bag', rightVal: 'Vrac, sacs, big bag' },
    ],
    winnerFr: 'CPJ 45 pour le courant, CPJ 55 pour les ouvrages exigeants',
    winnerEn: 'CPJ 45 for standard, CPJ 55 for demanding structures',
  },
  {
    slug: 'vrac-vs-sacs',
    titleFr: 'Ciment Vrac vs Sacs : Comparatif',
    titleEn: 'Bulk vs Bags Cement: Comparison',
    descFr: 'Vrac ou sacs ? Comparatif pour choisir le bon conditionnement de ciment.',
    descEn: 'Bulk or bags? Comparison to choose the right cement packaging.',
    leftLabel: 'Vrac',
    rightLabel: 'Sacs 50kg',
    rows: [
      { feature: 'Prix', leftVal: '1 500 DH/T', rightVal: '1 550 DH/T' },
      { feature: 'Quantité min', leftVal: '30 T', rightVal: '1 sac (50kg)' },
      { feature: 'Équipement requis', leftVal: 'Silo chantier', rightVal: 'Aucun' },
      { feature: 'Gros chantiers', leftVal: '✓ Optimal', rightVal: 'Moins adapté' },
      { feature: 'Petits chantiers', leftVal: 'Non adapté', rightVal: '✓ Optimal' },
      { feature: 'Manutention', leftVal: 'Pompage auto', rightVal: 'Manuelle' },
      { feature: 'Pertes', leftVal: 'Minimes', rightVal: 'Possibles' },
    ],
    winnerFr: 'Vrac pour >30T avec silo, sacs pour petits chantiers',
    winnerEn: 'Bulk for >30T with silo, bags for small sites',
  },
  {
    slug: 'sacs-vs-big-bag',
    titleFr: 'Sacs 50kg vs Big Bag : Comparatif',
    titleEn: '50kg Bags vs Big Bag: Comparison',
    descFr: 'Sacs ou big bag ? Comparatif des conditionnements ciment.',
    descEn: 'Bags or big bag? Cement packaging comparison.',
    leftLabel: 'Sacs 50kg',
    rightLabel: 'Big Bag 1T',
    rows: [
      { feature: 'Prix', leftVal: '1 550 DH/T', rightVal: '1 580 DH/T' },
      { feature: 'Poids unitaire', leftVal: '50 kg', rightVal: '1 000 kg' },
      { feature: 'Manutention', leftVal: 'Manuelle', rightVal: 'Grue/chariot' },
      { feature: 'Petits chantiers', leftVal: '✓ Optimal', rightVal: 'Possible' },
      { feature: 'Chantiers moyens', leftVal: 'Possible', rightVal: '✓ Optimal' },
      { feature: 'Stockage', leftVal: 'Local sec', rightVal: 'Extérieur possible' },
    ],
    winnerFr: 'Sacs pour maçonnerie, big bag pour chantiers moyens',
    winnerEn: 'Bags for masonry, big bag for medium sites',
  },
  {
    slug: 'vrac-vs-big-bag',
    titleFr: 'Vrac vs Big Bag : Comparatif',
    titleEn: 'Bulk vs Big Bag: Comparison',
    descFr: 'Vrac ou big bag ? Comparatif pour gros volumes de ciment.',
    descEn: 'Bulk or big bag? Comparison for large cement volumes.',
    leftLabel: 'Vrac',
    rightLabel: 'Big Bag 1T',
    rows: [
      { feature: 'Prix', leftVal: '1 500 DH/T', rightVal: '1 580 DH/T' },
      { feature: 'Quantité min', leftVal: '30 T', rightVal: '1 T' },
      { feature: 'Silo requis', leftVal: '✓ Oui', rightVal: '✗ Non' },
      { feature: 'Gros chantiers', leftVal: '✓ Optimal', rightVal: 'Possible' },
      { feature: 'Flexibilité', leftVal: 'Faible', rightVal: '✓ Élevée' },
    ],
    winnerFr: 'Vrac pour gros volumes avec silo, big bag sinon',
    winnerEn: 'Bulk for large volumes with silo, big bag otherwise',
  },
  {
    slug: 'ciment-vs-beton',
    titleFr: 'Ciment vs Béton : Quelle Différence ?',
    titleEn: 'Cement vs Concrete: What\'s the Difference?',
    descFr: 'Ciment et béton : quelle différence ? Explication complète.',
    descEn: 'Cement and concrete: what\'s the difference? Complete explanation.',
    leftLabel: 'Ciment',
    rightLabel: 'Béton',
    rows: [
      { feature: 'Nature', leftVal: 'Liant (poudre)', rightVal: 'Matériau composite' },
      { feature: 'Composition', leftVal: 'Clinker + gypse', rightVal: 'Ciment + granulats + eau' },
      { feature: 'Usage', leftVal: 'Composant du béton', rightVal: 'Matériau de construction' },
      { feature: 'Résistance', leftVal: 'N/A (liant)', rightVal: '20-50+ MPa' },
      { feature: 'Conditionnement', leftVal: 'Sacs, vrac, big bag', rightVal: 'Toupie, pompe' },
    ],
    winnerFr: 'Le ciment est un composant du béton',
    winnerEn: 'Cement is a component of concrete',
  },
  {
    slug: 'cpj45-vs-ciment-blanc',
    titleFr: 'CPJ 45 vs Ciment Blanc',
    titleEn: 'CPJ 45 vs White Cement',
    descFr: 'Comparatif ciment gris CPJ 45 et ciment blanc',
    descEn: 'Grey CPJ 45 vs white cement comparison',
    leftLabel: 'CPJ 45',
    rightLabel: 'Ciment Blanc',
    rows: [{ feature: 'Couleur', leftVal: 'Gris', rightVal: 'Blanc' }, { feature: 'Résistance', leftVal: '45 MPa', rightVal: '40 MPa' }, { feature: 'Prix', leftVal: '1 500 DH/T', rightVal: '3 500 DH/T' }, { feature: 'Usage structurel', leftVal: '✓ Oui', rightVal: 'Limité' }, { feature: 'Usage décoratif', leftVal: 'Non', rightVal: '✓ Oui' }, { feature: 'Disponibilité', leftVal: 'Large', rightVal: 'Limitée' }],
    winnerFr: 'CPJ 45 pour structure, ciment blanc pour décoration',
    winnerEn: 'CPJ 45 for structure, white cement for decoration',
  },
  {
    slug: 'cpj55-vs-ciment-blanc',
    titleFr: 'CPJ 55 vs Ciment Blanc',
    titleEn: 'CPJ 55 vs White Cement',
    descFr: 'Comparatif CPJ 55 et ciment blanc',
    descEn: 'CPJ 55 vs white cement comparison',
    leftLabel: 'CPJ 55',
    rightLabel: 'Ciment Blanc',
    rows: [{ feature: 'Résistance', leftVal: '55 MPa', rightVal: '40 MPa' }, { feature: 'Prix', leftVal: '1 600 DH/T', rightVal: '3 500 DH/T' }, { feature: 'Usage génie civil', leftVal: '✓ Optimal', rightVal: 'Non adapté' }, { feature: 'Usage carrelage', leftVal: 'Possible', rightVal: '✓ Optimal' }],
    winnerFr: 'CPJ 55 pour résistance, ciment blanc pour esthétique',
    winnerEn: 'CPJ 55 for strength, white cement for aesthetics',
  },
  {
    slug: 'ciment-vs-ciment-pouzzolanique',
    titleFr: 'Ciment Portland vs Pouzzolanique',
    titleEn: 'Portland vs Pozzolanic Cement',
    descFr: 'Comparatif ciment Portland et pouzzolanique',
    descEn: 'Portland vs pozzolanic cement comparison',
    leftLabel: 'CPJ 45',
    rightLabel: 'Pouzzolanique',
    rows: [{ feature: 'Résistance initiale', leftVal: '✓ Rapide', rightVal: 'Lente' }, { feature: 'Résistance long terme', leftVal: 'Standard', rightVal: '✓ Supérieure' }, { feature: 'Résistance chimique', leftVal: 'Standard', rightVal: '✓ Supérieure' }, { feature: 'Prix', leftVal: '1 500 DH/T', rightVal: '1 600 DH/T' }],
    winnerFr: 'Portland pour rapidité, pouzzolanique pour durabilité',
    winnerEn: 'Portland for speed, pozzolanic for durability',
  },
  {
    slug: 'ciment-vs-ciment-alumineux',
    titleFr: 'Ciment Portland vs Alumineux',
    titleEn: 'Portland vs Aluminous Cement',
    descFr: 'Comparatif ciment Portland et alumineux',
    descEn: 'Portland vs aluminous cement comparison',
    leftLabel: 'CPJ 45',
    rightLabel: 'Alumineux',
    rows: [{ feature: 'Résistance chaleur', leftVal: 'Standard', rightVal: '✓ Haute' }, { feature: 'Prise', leftVal: '45 min', rightVal: '✓ Rapide' }, { feature: 'Prix', leftVal: '1 500 DH/T', rightVal: '4 000 DH/T' }, { feature: 'Disponibilité', leftVal: 'Large', rightVal: 'Spécialisé' }],
    winnerFr: 'Portland pour usage courant, alumineux pour haute température',
    winnerEn: 'Portland for general use, aluminous for high temp',
  },
  {
    slug: 'beton-arme-vs-beton-non-arme',
    titleFr: 'Béton Armé vs Non Armé',
    titleEn: 'Reinforced vs Plain Concrete',
    descFr: 'Comparatif béton armé et béton non armé',
    descEn: 'Reinforced vs plain concrete comparison',
    leftLabel: 'Béton Armé',
    rightLabel: 'Béton Non Armé',
    rows: [{ feature: 'Armatures', leftVal: '✓ Acier HA', rightVal: 'Aucune' }, { feature: 'Résistance traction', leftVal: '✓ Élevée', rightVal: 'Faible' }, { feature: 'Usage structurel', leftVal: '✓ Poteaux, poutres', rightVal: 'Fondations simples' }, { feature: 'Coût', leftVal: 'Plus élevé', rightVal: 'Moins élevé' }],
    winnerFr: 'Béton armé pour structure, non armé pour fondations simples',
    winnerEn: 'Reinforced for structure, plain for simple foundations',
  },
  {
    slug: 'beton-plein-vs-beton-cellulaire',
    titleFr: 'Béton Plein vs Cellulaire',
    titleEn: 'Solid vs Cellular Concrete',
    descFr: 'Comparatif béton plein et béton cellulaire',
    descEn: 'Solid vs cellular concrete comparison',
    leftLabel: 'Béton Plein',
    rightLabel: 'Béton Cellulaire',
    rows: [{ feature: 'Densité', leftVal: '2 400 kg/m³', rightVal: '500 kg/m³' }, { feature: 'Isolation thermique', leftVal: 'Faible', rightVal: '✓ Excellente' }, { feature: 'Résistance', leftVal: '✓ Élevée', rightVal: 'Faible' }, { feature: 'Poids', leftVal: 'Lourd', rightVal: '✓ Léger' }],
    winnerFr: 'Béton plein pour structure, cellulaire pour isolation',
    winnerEn: 'Solid for structure, cellular for insulation',
  },
  {
    slug: 'beton-prefabrique-vs-coulé',
    titleFr: 'Béton Préfabriqué vs Coulé',
    titleEn: 'Precast vs Cast-in-Place Concrete',
    descFr: 'Comparatif béton préfabriqué et coulé sur place',
    descEn: 'Precast vs cast-in-place concrete comparison',
    leftLabel: 'Préfabriqué',
    rightLabel: 'Coulé sur place',
    rows: [{ feature: 'Qualité', leftVal: '✓ Contrôlée', rightVal: 'Variable' }, { feature: 'Délai installation', leftVal: '✓ Rapide', rightVal: 'Plus long' }, { feature: 'Coût transport', leftVal: 'Élevé', rightVal: 'N/A' }, { feature: 'Personnalisation', leftVal: 'Limitée', rightVal: '✓ Totale' }],
    winnerFr: 'Préfabriqué pour standardisation, coulé pour personnalisation',
    winnerEn: 'Precast for standardization, cast for customization',
  },
  {
    slug: 'ciment-sac-50-vs-25',
    titleFr: 'Sac 50kg vs Sac 25kg',
    titleEn: '50kg vs 25kg Bag',
    descFr: 'Comparatif sacs de ciment 50kg et 25kg',
    descEn: '50kg vs 25kg cement bag comparison',
    leftLabel: 'Sac 50kg',
    rightLabel: 'Sac 25kg',
    rows: [{ feature: 'Prix par kg', leftVal: '30 DH', rightVal: '35 DH' }, { feature: 'Manutention', leftVal: 'Difficile', rightVal: '✓ Facile' }, { feature: 'Gaspillage', leftVal: 'Faible', rightVal: 'Plus élevé' }, { feature: 'Usage', leftVal: 'Chantiers', rightVal: 'Particuliers' }],
    winnerFr: '50kg pour chantiers, 25kg pour bricolage',
    winnerEn: '50kg for sites, 25kg for DIY',
  },
  {
    slug: 'ciment-frais-vs-ancien',
    titleFr: 'Ciment Frais vs Ancien',
    titleEn: 'Fresh vs Old Cement',
    descFr: 'Comparatif ciment frais et ciment ancien',
    descEn: 'Fresh vs old cement comparison',
    leftLabel: 'Ciment Frais',
    rightLabel: 'Ciment Ancien',
    rows: [{ feature: 'Résistance', leftVal: '✓ Maximale', rightVal: 'Réduite' }, { feature: 'Prise', leftVal: '✓ Normale', rightVal: 'Retardée' }, { feature: 'Grumeaux', leftVal: 'Aucun', rightVal: '✓ Présents' }, { feature: 'Recommandation', leftVal: '✓ Utiliser', rightVal: 'Jeter' }],
    winnerFr: 'Toujours utiliser du ciment frais (max 3 mois)',
    winnerEn: 'Always use fresh cement (max 3 months)',
  },
  {
    slug: 'ciment-dam-vs-concurrents',
    titleFr: 'DAM vs Concurrents',
    titleEn: 'DAM vs Competitors',
    descFr: 'Comparatif Dakhla Aménagement vs concurrents',
    descEn: 'Dakhla Aménagement vs competitors comparison',
    leftLabel: 'DAM',
    rightLabel: 'Concurrents',
    rows: [{ feature: 'Production locale', leftVal: '✓ Dakhla', rightVal: 'Importée' }, { feature: 'Qualité', leftVal: '✓ NM 10.1.004', rightVal: 'Variable' }, { feature: 'Prix', leftVal: '✓ Dès 1500 DH/T', rightVal: 'Plus cher' }, { feature: 'Délai livraison', leftVal: '✓ Rapide', rightVal: 'Plus long' }],
    winnerFr: 'DAM : production locale, qualité, prix, délais',
    winnerEn: 'DAM: local production, quality, price, speed',
  },
  {
    slug: 'beton-pompe-vs-grue',
    titleFr: 'Béton Pompe vs Grue',
    titleEn: 'Pumped vs Crane Concrete',
    descFr: 'Comparatif béton pompé et béton à la grue',
    descEn: 'Pumped vs crane concrete comparison',
    leftLabel: 'Pompe',
    rightLabel: 'Grue',
    rows: [{ feature: 'Hauteur maximale', leftVal: '100m+', rightVal: '60m' }, { feature: 'Vitesse', leftVal: '✓ Rapide', rightVal: 'Lente' }, { feature: 'Coût', leftVal: 'Plus élevé', rightVal: 'Moins élevé' }, { feature: 'Usage', leftVal: 'Grands chantiers', rightVal: 'Chantiers moyens' }],
    winnerFr: 'Pompe pour hauteur et vitesse, grue pour coût',
    winnerEn: 'Pump for height and speed, crane for cost',
  },
  {
    slug: 'ciment-fournisseur-direct-vs-distributeur',
    titleFr: 'Direct vs Distributeur',
    titleEn: 'Direct vs Distributor',
    descFr: 'Acheter ciment direct vs distributeur',
    descEn: 'Buy cement direct vs distributor',
    leftLabel: 'Direct (DAM)',
    rightLabel: 'Distributeur',
    rows: [{ feature: 'Prix', leftVal: '✓ Usine', rightVal: 'Majoré' }, { feature: 'Quantité min', leftVal: '30T', rightVal: '1 sac' }, { feature: 'Délai', leftVal: 'Variable', rightVal: '✓ Immédiat' }, { feature: 'Support technique', leftVal: '✓ Expert', rightVal: 'Limité' }],
    winnerFr: 'Direct pour gros volumes, distributeur pour petits',
    winnerEn: 'Direct for bulk, distributor for small quantities',
  },
  {
    slug: 'ciment-vrac-citerne-vs-silo-mobile',
    titleFr: 'Citerne vs Silo Mobile',
    titleEn: 'Tanker vs Mobile Silo',
    descFr: 'Ciment vrac : citerne vs silo mobile',
    descEn: 'Bulk cement: tanker vs mobile silo',
    leftLabel: 'Citerne',
    rightLabel: 'Silo Mobile',
    rows: [{ feature: 'Capacité', leftVal: '30T', rightVal: '5-20T' }, { feature: 'Flexibilité', leftVal: 'Faible', rightVal: '✓ Élevée' }, { feature: 'Installation', leftVal: 'Silo fixe requis', rightVal: '✓ Autonome' }, { feature: 'Coût', leftVal: 'Moins élevé', rightVal: 'Plus élevé' }],
    winnerFr: 'Citerne pour gros chantiers, silo mobile pour flexibilité',
    winnerEn: 'Tanker for large sites, mobile silo for flexibility',
  },
  {
    slug: 'ciment-pour-béton-vs-mortier',
    titleFr: 'Béton vs Mortier',
    titleEn: 'Concrete vs Mortar',
    descFr: 'Ciment pour béton vs ciment pour mortier',
    descEn: 'Cement for concrete vs mortar',
    leftLabel: 'Béton',
    rightLabel: 'Mortier',
    rows: [{ feature: 'Granulats', leftVal: 'Sable + gravier', rightVal: 'Sable seulement' }, { feature: 'Résistance', leftVal: '✓ Élevée', rightVal: 'Moyenne' }, { feature: 'Usage', leftVal: 'Structure', rightVal: 'Liaison, enduit' }, { feature: 'Dosage', leftVal: '350 kg/m³', rightVal: '300-500 kg/m³' }],
    winnerFr: 'Béton pour structure, mortier pour liaison et enduit',
    winnerEn: 'Concrete for structure, mortar for bonding',
  },
  {
    slug: 'ciment-cpj45-vs-ciments-speciaux',
    titleFr: 'CPJ 45 vs Ciments Spéciaux',
    titleEn: 'CPJ 45 vs Special Cements',
    descFr: 'CPJ 45 vs ciments spéciaux (réfractaire, alumineux)',
    descEn: 'CPJ 45 vs special cements',
    leftLabel: 'CPJ 45',
    rightLabel: 'Ciments Spéciaux',
    rows: [{ feature: 'Disponibilité', leftVal: '✓ Large', rightVal: 'Spécialisée' }, { feature: 'Prix', leftVal: '✓ 1500 DH/T', rightVal: '3000-5000 DH/T' }, { feature: 'Usage courant', leftVal: '✓ Optimal', rightVal: 'Non adapté' }, { feature: 'Usage spécifique', leftVal: 'Limité', rightVal: '✓ Optimal' }],
    winnerFr: 'CPJ 45 pour 95% des usages, ciments spéciaux pour cas particuliers',
    winnerEn: 'CPJ 45 for 95% of uses, special for specific cases',
  },
  {
    slug: 'ciment-cpj55-vs-ciments-speciaux',
    titleFr: 'CPJ 55 vs Ciments Spéciaux',
    titleEn: 'CPJ 55 vs Special Cements',
    descFr: 'CPJ 55 vs ciments spéciaux',
    descEn: 'CPJ 55 vs special cements',
    leftLabel: 'CPJ 55',
    rightLabel: 'Ciments Spéciaux',
    rows: [{ feature: 'Résistance', leftVal: '55 MPa', rightVal: 'Variable' }, { feature: 'Prix', leftVal: '✓ 1600 DH/T', rightVal: '3000-5000 DH/T' }, { feature: 'Usage génie civil', leftVal: '✓ Optimal', rightVal: 'Selon type' }, { feature: 'Usage extrême', leftVal: 'Limité', rightVal: '✓ Optimal' }],
    winnerFr: 'CPJ 55 pour haute résistance, spéciaux pour conditions extrêmes',
    winnerEn: 'CPJ 55 for strength, special for extreme conditions',
  },
  {
    slug: 'beton-365j-vs-28j',
    titleFr: 'Béton 28j vs 365j',
    titleEn: '28-day vs 365-day Concrete',
    descFr: 'Résistance béton 28 jours vs 1 an',
    descEn: '28-day vs 365-day concrete strength',
    leftLabel: '28 jours',
    rightLabel: '365 jours',
    rows: [{ feature: 'Résistance', leftVal: '100%', rightVal: '✓ 120-130%' }, { feature: 'Prise complète', leftVal: '✓ Référence', rightVal: 'Continue' }, { feature: 'Contrôle qualité', leftVal: '✓ Standard', rightVal: 'Long terme' }, { feature: 'Pratique', leftVal: '✓ Utilisable', rightVal: 'Théorique' }],
    winnerFr: 'Référence à 28 jours, gain de 20-30% à 1 an',
    winnerEn: 'Reference at 28 days, 20-30% gain at 1 year',
  },
  {
    slug: 'ciment-hydraulique-vs-non-hydraulique',
    titleFr: 'Hydraulique vs Non-Hydraulique',
    titleEn: 'Hydraulic vs Non-Hydraulic',
    descFr: 'Ciment hydraulique vs non-hydraulique',
    descEn: 'Hydraulic vs non-hydraulic cement',
    leftLabel: 'Hydraulique',
    rightLabel: 'Non-Hydraulique',
    rows: [{ feature: "Prise dans l'eau", leftVal: '✓ Oui', rightVal: 'Non' }, { feature: 'Résistance humidité', leftVal: '✓ Excellente', rightVal: 'Faible' }, { feature: 'Usage extérieur', leftVal: '✓ Optimal', rightVal: 'Limité' }, { feature: 'Exemples', leftVal: 'CPJ 45, CPJ 55', rightVal: 'Chaux aérienne' }],
    winnerFr: "Hydraulique pour résistance à l'eau, non-hydraulique pour intérieur",
    winnerEn: 'Hydraulic for water resistance, non for interior',
  },
  {
    slug: 'ciment-avec-vs-sans-adjuvants',
    titleFr: 'Avec vs Sans Adjuvants',
    titleEn: 'With vs Without Admixtures',
    descFr: 'Béton avec vs sans adjuvants',
    descEn: 'Concrete with vs without admixtures',
    leftLabel: 'Avec Adjuvants',
    rightLabel: 'Sans Adjuvants',
    rows: [{ feature: 'Maniabilité', leftVal: '✓ Ajustable', rightVal: 'Standard' }, { feature: 'Résistance', leftVal: '✓ Optimisée', rightVal: 'Standard' }, { feature: 'Coût', leftVal: 'Plus élevé', rightVal: '✓ Moins élevé' }, { feature: 'Complexité', leftVal: 'Plus complexe', rightVal: '✓ Simple' }],
    winnerFr: 'Adjuvants pour performance, sans pour simplicité',
    winnerEn: 'Admixtures for performance, without for simplicity',
  },
  {
    slug: 'ciment-stockage-interieur-vs-exterieur',
    titleFr: 'Stockage Intérieur vs Extérieur',
    titleEn: 'Indoor vs Outdoor Storage',
    descFr: 'Stockage ciment en intérieur vs extérieur',
    descEn: 'Indoor vs outdoor cement storage',
    leftLabel: 'Intérieur',
    rightLabel: 'Extérieur',
    rows: [{ feature: 'Protection humidité', leftVal: '✓ Excellente', rightVal: 'Faible' }, { feature: 'Durée conservation', leftVal: '✓ 3 mois', rightVal: '1 mois' }, { feature: 'Coût', leftVal: 'Plus élevé', rightVal: '✓ Moins élevé' }, { feature: 'Risque détérioration', leftVal: 'Faible', rightVal: '✓ Élevé' }],
    winnerFr: 'Stockage intérieur obligatoire pour préserver la qualité',
    winnerEn: 'Indoor storage mandatory to preserve quality',
  },
  {
    slug: 'ciment-vs-chaux',
    titleFr: 'Ciment vs Chaux : Comparatif',
    titleEn: 'Cement vs Lime: Comparison',
    descFr: 'Ciment ou chaux ? Différences, usages et quand utiliser chacun.',
    descEn: 'Cement or lime? Differences, uses and when to use each.',
    leftLabel: 'Ciment',
    rightLabel: 'Chaux',
    rows: [
      { feature: 'Résistance', leftVal: '45-55 MPa', rightVal: '5-15 MPa' },
      { feature: 'Prise', leftVal: 'Rapide (45min)', rightVal: 'Lente (jours)' },
      { feature: 'Béton armé', leftVal: '✓ Adapté', rightVal: '✗ Non adapté' },
      { feature: 'Restauration', leftVal: 'Possible', rightVal: '✓ Recommandé' },
      { feature: 'Enduits traditionnels', leftVal: 'Possible', rightVal: '✓ Recommandé' },
      { feature: 'Prix', leftVal: '1 500 DH/T', rightVal: '2 000 DH/T' },
    ],
    winnerFr: 'Ciment pour structure, chaux pour restauration',
    winnerEn: 'Cement for structure, lime for restoration',
  },
];

export function getComparison(slug: string): CementComparison | undefined {
  return COMPARISONS.find((c) => c.slug === slug);
}
